<?php
// config/preferences.php

return [
    'notifications' => [
        'title' => 'Notifications',
        'description' => 'Manage how you receive notifications',
        'icon' => 'bell',
        'order' => 1,
        'fields' => [
            'email_alerts' => [
                'type' => 'boolean',
                'label' => 'Email Alerts',
                'description' => 'Receive important notifications via email',
                'default' => true,
                'order' => 1,
            ],
            'sms_alerts' => [
                'type' => 'boolean',
                'label' => 'SMS Alerts',
                'description' => 'Receive critical alerts via SMS',
                'default' => false,
                'order' => 2,
            ],
            'push_notifications' => [
                'type' => 'boolean',
                'label' => 'Push Notifications',
                'description' => 'Receive browser push notifications',
                'default' => true,
                'order' => 3,
            ],
            'marketing_emails' => [
                'type' => 'boolean',
                'label' => 'Marketing Emails',
                'description' => 'Receive product updates and promotional content',
                'default' => false,
                'order' => 4,
            ],
            'digest_frequency' => [
                'type' => 'select',
                'label' => 'Email Digest Frequency',
                'description' => 'How often to receive digest emails',
                'options' => [
                    'never' => 'Never',
                    'daily' => 'Daily',
                    'weekly' => 'Weekly',
                    'monthly' => 'Monthly',
                ],
                'default' => 'weekly',
                'order' => 5,
            ],
        ],
    ],
    'ui' => [
        'title' => 'Interface & Display',
        'description' => 'Customize your user interface preferences',
        'icon' => 'cog',
        'order' => 2,
        'fields' => [
            'dark_mode' => [
                'type' => 'boolean',
                'label' => 'Dark Mode',
                'description' => 'Use dark theme for better viewing in low light',
                'default' => false,
                'order' => 1,
            ],
            'language' => [
                'type' => 'select',
                'label' => 'Language',
                'description' => 'Choose your preferred language',
                'options' => [
                    'en' => 'English',
                    'es' => 'Spanish',
                    'fr' => 'French',
                    'de' => 'German',
                    'it' => 'Italian',
                    'pt' => 'Portuguese',
                    'nl' => 'Dutch',
                    'ru' => 'Russian',
                ],
                'default' => 'en',
                'order' => 2,
            ],
            'timezone' => [
                'type' => 'select',
                'label' => 'Timezone',
                'description' => 'Your local timezone',
                'options' => [
                    'America/Los_Angeles' => 'UTC-8 (Pacific Time)',
                    'America/Denver' => 'UTC-7 (Mountain Time)',
                    'America/Chicago' => 'UTC-6 (Central Time)',
                    'America/New_York' => 'UTC-5 (Eastern Time)',
                    'UTC' => 'UTC+0 (Greenwich Time)',
                    'Europe/London' => 'UTC+0 (London Time)',
                    'Europe/Paris' => 'UTC+1 (Central European Time)',
                    'Europe/Berlin' => 'UTC+1 (Berlin Time)',
                    'Asia/Tokyo' => 'UTC+9 (Japan Time)',
                    'Asia/Shanghai' => 'UTC+8 (China Time)',
                    'Australia/Sydney' => 'UTC+10 (Sydney Time)',
                ],
                'default' => 'UTC',
                'order' => 3,
            ],
            'date_format' => [
                'type' => 'select',
                'label' => 'Date Format',
                'description' => 'How dates should be displayed',
                'options' => [
                    'm/d/Y' => 'MM/DD/YYYY (US)',
                    'd/m/Y' => 'DD/MM/YYYY (European)',
                    'Y-m-d' => 'YYYY-MM-DD (ISO)',
                    'M j, Y' => 'Month Day, Year',
                    'j F Y' => 'Day Month Year',
                ],
                'default' => 'm/d/Y',
                'order' => 4,
            ],
            'time_format' => [
                'type' => 'select',
                'label' => 'Time Format',
                'description' => 'How time should be displayed',
                'options' => [
                    '12' => '12 Hour (AM/PM)',
                    '24' => '24 Hour',
                ],
                'default' => '12',
                'order' => 5,
            ],
            'items_per_page' => [
                'type' => 'select',
                'label' => 'Items per Page',
                'description' => 'Number of items to display per page',
                'options' => [
                    '10' => '10',
                    '25' => '25',
                    '50' => '50',
                    '100' => '100',
                ],
                'default' => '25',
                'order' => 6,
            ],
            'show_tips' => [
                'type' => 'boolean',
                'label' => 'Show Tips',
                'description' => 'Display helpful tips and tutorials',
                'default' => true,
                'order' => 7,
            ],
        ],
    ],
    'privacy' => [
        'title' => 'Privacy & Security',
        'description' => 'Control your privacy and data sharing preferences',
        'icon' => 'shield-check',
        'order' => 3,
        'fields' => [
            'public_profile' => [
                'type' => 'boolean',
                'label' => 'Public Profile',
                'description' => 'Make your profile visible to other users',
                'default' => false,
                'order' => 1,
            ],
            'search_indexing' => [
                'type' => 'boolean',
                'label' => 'Search Engine Indexing',
                'description' => 'Allow search engines to index your profile',
                'default' => false,
                'order' => 2,
            ],
            'show_activity' => [
                'type' => 'boolean',
                'label' => 'Activity Status',
                'description' => 'Show when you\'re online to other users',
                'default' => true,
                'order' => 3,
            ],
            'data_sharing' => [
                'type' => 'select',
                'label' => 'Data Sharing',
                'description' => 'Control how your data is shared for analytics',
                'options' => [
                    'none' => 'No sharing',
                    'anonymous' => 'Anonymous analytics only',
                    'full' => 'Full sharing (helps improve service)',
                ],
                'default' => 'anonymous',
                'order' => 4,
            ],
            'contact_visibility' => [
                'type' => 'select',
                'label' => 'Contact Information Visibility',
                'description' => 'Who can see your contact information',
                'options' => [
                    'private' => 'Only me',
                    'friends' => 'Friends only',
                    'members' => 'All members',
                    'public' => 'Everyone',
                ],
                'default' => 'private',
                'order' => 5,
            ],
        ],
    ],
    'editor' => [
        'title' => 'Editor & Workspace',
        'description' => 'Customize your editing and workspace experience',
        'icon' => 'pencil',
        'order' => 4,
        'fields' => [
            'auto_save' => [
                'type' => 'boolean',
                'label' => 'Auto-save',
                'description' => 'Automatically save your work as you type',
                'default' => true,
                'order' => 1,
            ],
            'auto_backup' => [
                'type' => 'boolean',
                'label' => 'Auto-backup',
                'description' => 'Create automatic backups of your work',
                'default' => true,
                'order' => 2,
            ],
            'save_interval' => [
                'type' => 'select',
                'label' => 'Auto-save Interval',
                'description' => 'How often to auto-save your work',
                'options' => [
                    '30' => 'Every 30 seconds',
                    '60' => 'Every minute',
                    '300' => 'Every 5 minutes',
                    '600' => 'Every 10 minutes',
                ],
                'default' => '60',
                'order' => 3,
            ],
            'editor_theme' => [
                'type' => 'select',
                'label' => 'Editor Theme',
                'description' => 'Choose your preferred editor appearance',
                'options' => [
                    'default' => 'Default',
                    'minimal' => 'Minimal',
                    'focus' => 'Focus Mode',
                    'classic' => 'Classic',
                    'modern' => 'Modern',
                ],
                'default' => 'default',
                'order' => 4,
            ],
            'spell_check' => [
                'type' => 'boolean',
                'label' => 'Spell Check',
                'description' => 'Enable spell checking in editor',
                'default' => true,
                'order' => 5,
            ],
        ],
    ],
];